name: trello_application
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.9
  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  http: ^1.3.0
  blackfoot_flutter_lint: ^2.0.0
  flutter_dotenv: ^5.2.1
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env